version: '3.8'
services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    env_file:
      - .env
    volumes:
      - .:/app  # Mounts the local project directory to the container
    restart: always